[package]
name = "secretstore"
version = "0.1.2"
description = "Store a secret (such as a private key) in an encrypted file"
license = "MIT"
edition = "2021"

[dependencies]
hex-conservative = "0.3.0"
rand = "0.9.0"
sha256 = "1.6.0"
