name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set up Rust
      run: rustup override set 1.81
    - uses: actions/checkout@v4
    - name: Build with default features
      run: cargo build --verbose
    - name: Build
      run: cargo build --features accesssecret --verbose
    - name: Run tests
      run: cargo test --features accesssecret --verbose
